---

- name: create minio group
  group:
    name: "{{ minio_group }}"
    system: true

- name: create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: true

- name: create volume directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "ug=rwx,o="
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  loop: "{{ minio_volumes }}"

- name: install minio binary
  copy:
    src: minio
    dest: /usr/local/bin/minio
    mode: "a=rx"
    checksum: aa279fe2da03bf141818114e9c2f14dfb2f9d497

- name: install minio configuration file
  template:
    src: default.j2
    dest: /etc/default/minio
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "ug=r,o="
  notify: restart minio

- name: install minio systemd service file
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: start and enable minio service
  systemd:
    state: started
    name: minio
    enabled: true
    daemon_reload: true
  notify: restart minio
